platform :ios, '7.0'
pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
pod 'UMengAnalytics'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Color-Picker-for-iOS', '~> 2.0'
